//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Exercise_03_10_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_LOGIN_DATE
    {
        public int ID { get; set; }
        public string USER_ID { get; set; }
        public string PASSWD { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    }
}
