//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Exercise_03_10_2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_REGISTRATION_DATA
    {
        public int ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string USER_EMAIL { get; set; }
        public string PASSWD { get; set; }
        public Nullable<long> CONTACT_NUMBER { get; set; }
        public string USER_ADDR { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
