//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Exercise_03_10_2020.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WEB_API_DATAEntities : DbContext
    {
        public WEB_API_DATAEntities()
            : base("name=WEB_API_DATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<USER_LOGIN_DATE> USER_LOGIN_DATE { get; set; }
        public virtual DbSet<USER_REGISTRATION_DATA> USER_REGISTRATION_DATA { get; set; }
    }
}
